# Generated by Django 4.2.4 on 2023-09-10 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 19, 17, 3, 455721)),
        ),
    ]
