# Generated by Django 4.2.4 on 2023-09-10 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppToDo', '0003_alter_todomodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 10, 23, 51, 22, 736319)),
        ),
    ]
